In [256]:
import numpy as np
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [257]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [258]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [278]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [260]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [261]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [262]:
choi = [0,1,2],[3,4,5],[6,7,8]
np.array(choi)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [263]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [264]:
np.random.rand(1)

array([0.05332326])

In [ ]:
표준정규분포란

In [265]:
np.arange(0.01,101)

array([1.0000e-02, 1.0100e+00, 2.0100e+00, 3.0100e+00, 4.0100e+00,
       5.0100e+00, 6.0100e+00, 7.0100e+00, 8.0100e+00, 9.0100e+00,
       1.0010e+01, 1.1010e+01, 1.2010e+01, 1.3010e+01, 1.4010e+01,
       1.5010e+01, 1.6010e+01, 1.7010e+01, 1.8010e+01, 1.9010e+01,
       2.0010e+01, 2.1010e+01, 2.2010e+01, 2.3010e+01, 2.4010e+01,
       2.5010e+01, 2.6010e+01, 2.7010e+01, 2.8010e+01, 2.9010e+01,
       3.0010e+01, 3.1010e+01, 3.2010e+01, 3.3010e+01, 3.4010e+01,
       3.5010e+01, 3.6010e+01, 3.7010e+01, 3.8010e+01, 3.9010e+01,
       4.0010e+01, 4.1010e+01, 4.2010e+01, 4.3010e+01, 4.4010e+01,
       4.5010e+01, 4.6010e+01, 4.7010e+01, 4.8010e+01, 4.9010e+01,
       5.0010e+01, 5.1010e+01, 5.2010e+01, 5.3010e+01, 5.4010e+01,
       5.5010e+01, 5.6010e+01, 5.7010e+01, 5.8010e+01, 5.9010e+01,
       6.0010e+01, 6.1010e+01, 6.2010e+01, 6.3010e+01, 6.4010e+01,
       6.5010e+01, 6.6010e+01, 6.7010e+01, 6.8010e+01, 6.9010e+01,
       7.0010e+01, 7.1010e+01, 7.2010e+01, 7.3010e+01, 7.4010e

In [266]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [277]:
mat = [1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]
np.array(mat)
mat = np.array(mat)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [270]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [271]:
mat[3][4]

20

In [272]:
mat[:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [273]:
mat[4]

array([21, 22, 23, 24, 25])

In [274]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [280]:
mat.sum()

325